<?xml version="1.0"?>
<package format="2">
  <name>mushr_pf</name>
  <version>1.0.0</version>
  <description>Particle filter</description>
  <author>Lirui Wang</author>
  <author>Joseph Shieh</author>
  <author>Chi-Heng Hung</author>
  <author>Nansong Yi</author>

  <maintainer email="schmttle@cs.washington.edu">Schmittle</maintainer>

  <license>BSD</license>

  <build_depend>rclpy</build_depend>
  <build_depend>std_msgs</build_depend>
  <build_export_depend>rclpy</build_export_depend>
  <build_export_depend>std_msgs</build_export_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>vesc_msgs</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
